#!/bin/bash

aurora_bin=/opt/aurora/aurora
pre_cmd='bash -c '
post_cmd=''


runAurora(){
  $pre_cmd "killall aurora; $aurora_bin $post_cmd"
}


if [ $# -ne 0 ];  then

  for arg; do
      [[ ! $arg == '--with-root' ]] && args+=("$arg") || pre_cmd="pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY sh -c "
  done

  post_cmd="${args[@]}"


   if [[ "$@" == *"--help"* ]]; then
echo "usage: --log          -       enables logging
       --version      -       displays app version
       --with-root    -       runs with elevated privileges
       --help         -       helps!"
   else
    runAurora
   fi
else
    runAurora
fi
