name: aurora
description: An Alternate to Aura Sync for linux.

publish_to: 'none'

version: 3.7.9-beta+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.0.0
  flex_color_picker: ^3.7.0
  get_it: ^8.0.3
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  another_xlider: ^3.0.2
  another_stepper: ^1.2.2
  package_info_plus: ^8.2.1
  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  animated_text_kit: ^4.2.3
  equatable: ^2.0.7
  cupertino_icons: ^1.0.8
  bitsdojo_window: ^0.1.6
  window_manager: ^0.4.3
  responsive_sizer: ^3.3.1
  args: ^2.6.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: any

flutter:
  uses-material-design: true

  assets:
    - assets/scripts/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Play
      fonts:
        - asset: assets/fonts/Play-Regular.ttf
