name: aurora
description: An Alternate to Aura Sync for linux.

publish_to: 'none'

version: 2.6.9-beta+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  flex_color_picker: ^3.2.2
  get_it: ^7.6.0
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  rxdart: ^0.27.7
  another_xlider: ^3.0.1
  another_stepper: ^1.2.2
  package_info_plus: ^3.0.3
  dio: ^5.1.2
  url_launcher: ^6.1.11
  animated_text_kit: ^4.2.2
  equatable: ^2.0.5
  cupertino_icons: ^1.0.5
  bitsdojo_window: ^0.1.5
  flutter_phoenix: ^1.1.1
  window_manager: ^0.3.4
  responsive_sizer: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/scripts/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Play
      fonts:
        - asset: assets/fonts/Play-Regular.ttf
