name: aurora
description: An Alternate to Aura Sync for linux.

publish_to: 'none'

version: 3.4.6-beta+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  flex_color_picker: ^3.3.0
  get_it: ^7.6.2
  path_provider: ^2.1.1
  rxdart: ^0.27.7
  another_xlider: ^3.0.1
  another_stepper: ^1.2.2
  package_info_plus: ^3.1.2
  dio: ^5.3.2
  url_launcher: ^6.1.14
  animated_text_kit: ^4.2.2
  equatable: ^2.0.5
  cupertino_icons: ^1.0.6
  bitsdojo_window: ^0.1.5
  window_manager: ^0.3.6
  responsive_sizer: ^3.2.0
  args: ^2.4.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  dropdown_button2: ^2.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  isar_generator: ^3.1.0+1
  build_runner: any

flutter:
  uses-material-design: true

  assets:
    - assets/scripts/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Play
      fonts:
        - asset: assets/fonts/Play-Regular.ttf
