# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Aurora CI

on:

 push:
    branches: 
      - stable

jobs:
  build:
    name: "Building System"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2.4.0
               
    - name: Get Changelog
      id: changelog_id
      run: |
         MY_STRING=$(cat ./changelog.txt )
          MY_STRING="${MY_STRING//'%'/'%25'}"
          MY_STRING="${MY_STRING//$'\n'/'%0A'}"
          MY_STRING="${MY_STRING//$'\r'/'%0D'}"
         echo ::set-output name=changelog::$MY_STRING

   
          
    - name: Upload files to a GitHub release
      uses: svenstaro/upload-release-action@2.2.1
      with:
          # GitHub token.
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /usr/bin/git
          # Tag to use as a release.
          tag: "ttt"     
          body:   ${{join(steps.run_tests.outputs.*, '\n')}}${{ steps.changelog_id.outputs.changelog }}


          
           
