# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Aurora CI

on:

  push:
    branches:
      - stable
      - beta

jobs:
  build:
    name: "Build Aurora"
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: 'stable'

      - name: Install Linux build tools
        run: sudo apt-get update && sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev squashfs-tools libfuse2

      - name: Enable desktop
        run: flutter config --enable-linux-desktop

      - name: Install Cider
        run: flutter pub global activate cider

      - name: Get Version
        id: version_id
        run: echo "::set-output name=version::$(cider version)"

      - name: Get Changelog
        id: changelog_id
        run: |
          changelogs=$(cat ./changelog.txt )
           changelogs="${changelogs//'%'/'%25'}"
           changelogs="${changelogs//$'\n'/'%0A'}"
           changelogs="${changelogs//$'\r'/'%0D'}"
          echo ::set-output name=changelog::$changelogs

      - name: Get packages
        run: flutter pub get

      - name: Set Build Type
        run: sed -i "s/BuildType.debug/BuildType.appimage/g" lib/utility/constants.dart

      - name: Run code generator
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Flutter build app
        run: flutter build linux

      - name: Install AppImage Builder
        run: |
          wget -O appimage-builder-x86_64.AppImage https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage
          chmod +x appimage-builder-x86_64.AppImage
          sudo mv appimage-builder-x86_64.AppImage /usr/local/bin/appimage-builder

      - name: Build AppImage
        run:  appimage-builder --skip-tests

      - name: Rename AppImage
        run: mv legacy07-latest-x86_64.AppImage aurora-linux-${{ steps.version_id.outputs.version }}.AppImage

      - name: Build debian package
        run: |
          sed -i "s/BuildType.appimage/BuildType.deb/g" lib/utility/constants.dart      
          ./aurora_builder deb 

      - name: Build rpm package
        if: github.ref == 'refs/heads/stable'
        run: |
          sed -i "s/BuildType.deb/BuildType.rpm/g" lib/utility/constants.dart      
          ./aurora_builder "$PWD"    

      - name: Combine binaries
        run: |
          mkdir output
          if [ -f "/home/runner/rpmbuild/SRPMS/aurora-3.10.13-1.src.rpm" ]; then
            echo "SRPM exists"
          else
            echo "SRPM MISSING"
          fi
  
          mv aurora-linux-${{ steps.version_id.outputs.version }}.AppImage output/
          mv debian.deb output/aurora_${{ steps.version_id.outputs.version }}_amd64.deb

      - name: Trigger Copr Build
        if: github.ref == 'refs/heads/stable'
        continue-on-error: true
        env:
          COPR_LOGIN: ${{ secrets.COPR_LOGIN }}
          COPR_USERNAME: ${{ secrets.COPR_USERNAME }}
          COPR_TOKEN: ${{ secrets.COPR_TOKEN }}
          COPR_PROJECT_NAME: ${{ secrets.COPR_PROJECT_NAME }}
        run: |
          if ls output/*.src.rpm 1> /dev/null 2>&1; then
            echo "SRPM found. Installing Copr CLI..."
            sudo apt-get update && sudo apt-get install -y python3-pip libkrb5-dev
            pip3 install copr-cli
            
            echo "Configuring Copr..."
            mkdir -p ~/.config
            printf "[copr-cli]\nlogin = $COPR_LOGIN\nusername = $COPR_USERNAME\ntoken = $COPR_TOKEN\ncopr_url = https://copr.fedorainfracloud.org\n" > ~/.config/copr
            
            if [ -z "$COPR_PROJECT_NAME" ]; then
              echo "Error: COPR_PROJECT_NAME environment variable is not set."
              exit 1
            fi

            SRPM_FILE=$(ls output/*.src.rpm | head -n 1)
            echo "Found SRPM: $SRPM_FILE"

            echo "Triggering Copr build for project $COPR_PROJECT_NAME..."
            copr-cli build "$COPR_PROJECT_NAME" "$SRPM_FILE"
          else
            echo "No SRPM found, skipping Copr build."
          fi

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: output/*
          release_name: aurora-${{ steps.version_id.outputs.version }}
          tag: ${{ steps.version_id.outputs.version }}
          body:   ${{join(steps.run_tests.outputs.*, '\n')}}${{ steps.changelog_id.outputs.changelog }}
          overwrite: true
          file_glob: true
